/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ClaimExpiredCollateral
 * @category generated
 */
export const claimExpiredCollateralStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ClaimExpiredCollateralInstructionArgs'
)
/**
 * Accounts required by the _claimExpiredCollateral_ instruction
 *
 * @property [_writable_, **signer**] superOwner
 * @property [] globalState
 * @property [_writable_] treasuryWallet
 * @property [_writable_] offer
 * @property [_writable_] subOffer
 * @property [_writable_] userNftVault
 * @property [_writable_] borrowerNftVault
 * @property [] nftMint
 * @property [] edition
 * @property [] metadataProgram
 * @property [] clock
 * @category Instructions
 * @category ClaimExpiredCollateral
 * @category generated
 */
export type ClaimExpiredCollateralInstructionAccounts = {
  superOwner: web3.PublicKey
  globalState: web3.PublicKey
  treasuryWallet: web3.PublicKey
  offer: web3.PublicKey
  subOffer: web3.PublicKey
  userNftVault: web3.PublicKey
  borrowerNftVault: web3.PublicKey
  nftMint: web3.PublicKey
  edition: web3.PublicKey
  metadataProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  clock: web3.PublicKey
}

export const claimExpiredCollateralInstructionDiscriminator = [
  43, 176, 249, 0, 163, 168, 177, 195,
]

/**
 * Creates a _ClaimExpiredCollateral_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ClaimExpiredCollateral
 * @category generated
 */
export function createClaimExpiredCollateralInstruction(
  accounts: ClaimExpiredCollateralInstructionAccounts,
  programId = new web3.PublicKey('6oVXrGCdtnTUR6xCvn2Z3f2CYaiboAGar1DKxzeX8QYh')
) {
  const [data] = claimExpiredCollateralStruct.serialize({
    instructionDiscriminator: claimExpiredCollateralInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.superOwner,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.globalState,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryWallet,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.offer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.subOffer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userNftVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.borrowerNftVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.nftMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.edition,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.metadataProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
