/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category SetOffer
 * @category generated
 */
export const setOfferStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'SetOfferInstructionArgs'
)
/**
 * Accounts required by the _setOffer_ instruction
 *
 * @property [_writable_, **signer**] borrower
 * @property [_writable_, **signer**] payer
 * @property [_writable_] offer
 * @property [] nftMint
 * @property [] nftMetadata
 * @property [_writable_] userVault
 * @property [] edition
 * @property [] metadataProgram
 * @property [] clock
 * @category Instructions
 * @category SetOffer
 * @category generated
 */
export type SetOfferInstructionAccounts = {
  borrower: web3.PublicKey
  payer: web3.PublicKey
  offer: web3.PublicKey
  nftMint: web3.PublicKey
  nftMetadata: web3.PublicKey
  userVault: web3.PublicKey
  edition: web3.PublicKey
  metadataProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  rent?: web3.PublicKey
  clock: web3.PublicKey
}

export const setOfferInstructionDiscriminator = [
  230, 220, 7, 113, 40, 254, 223, 140,
]

/**
 * Creates a _SetOffer_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category SetOffer
 * @category generated
 */
export function createSetOfferInstruction(
  accounts: SetOfferInstructionAccounts,
  programId = new web3.PublicKey('6oVXrGCdtnTUR6xCvn2Z3f2CYaiboAGar1DKxzeX8QYh')
) {
  const [data] = setOfferStruct.serialize({
    instructionDiscriminator: setOfferInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.borrower,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.offer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.nftMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.nftMetadata,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.userVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.edition,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.metadataProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
