/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category SetStakingPool
 * @category generated
 */
export type SetStakingPoolInstructionArgs = {
  unlocStakingPid: web3.PublicKey
  unlocStakingPoolId: web3.PublicKey
}
/**
 * @category Instructions
 * @category SetStakingPool
 * @category generated
 */
export const setStakingPoolStruct = new beet.BeetArgsStruct<
  SetStakingPoolInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['unlocStakingPid', beetSolana.publicKey],
    ['unlocStakingPoolId', beetSolana.publicKey],
  ],
  'SetStakingPoolInstructionArgs'
)
/**
 * Accounts required by the _setStakingPool_ instruction
 *
 * @property [_writable_, **signer**] superOwner
 * @property [_writable_] globalState
 * @category Instructions
 * @category SetStakingPool
 * @category generated
 */
export type SetStakingPoolInstructionAccounts = {
  superOwner: web3.PublicKey
  globalState: web3.PublicKey
}

export const setStakingPoolInstructionDiscriminator = [
  244, 102, 45, 197, 42, 142, 109, 108,
]

/**
 * Creates a _SetStakingPool_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetStakingPool
 * @category generated
 */
export function createSetStakingPoolInstruction(
  accounts: SetStakingPoolInstructionAccounts,
  args: SetStakingPoolInstructionArgs,
  programId = new web3.PublicKey('6oVXrGCdtnTUR6xCvn2Z3f2CYaiboAGar1DKxzeX8QYh')
) {
  const [data] = setStakingPoolStruct.serialize({
    instructionDiscriminator: setStakingPoolInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.superOwner,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.globalState,
      isWritable: true,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
