/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category DelVotingItem
 * @category generated
 */
export const delVotingItemStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'DelVotingItemInstructionArgs'
)
/**
 * Accounts required by the _delVotingItem_ instruction
 *
 * @property [_writable_, **signer**] superOwner
 * @property [_writable_] globalState
 * @property [_writable_] voting
 * @property [_writable_] votingItem
 * @category Instructions
 * @category DelVotingItem
 * @category generated
 */
export type DelVotingItemInstructionAccounts = {
  superOwner: web3.PublicKey
  globalState: web3.PublicKey
  voting: web3.PublicKey
  votingItem: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  rent?: web3.PublicKey
}

export const delVotingItemInstructionDiscriminator = [
  172, 91, 208, 16, 11, 168, 54, 80,
]

/**
 * Creates a _DelVotingItem_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category DelVotingItem
 * @category generated
 */
export function createDelVotingItemInstruction(
  accounts: DelVotingItemInstructionAccounts,
  programId = new web3.PublicKey('6z6RuFauTG511XRakJnPhxUTCVPohv6oC69xieMdm4Z9')
) {
  const [data] = delVotingItemStruct.serialize({
    instructionDiscriminator: delVotingItemInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.superOwner,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.globalState,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.voting,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.votingItem,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
