/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type DurationExtraRewardConfig = {
  duration: beet.bignum
  extraPercentage: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const durationExtraRewardConfigBeet =
  new beet.BeetArgsStruct<DurationExtraRewardConfig>(
    [
      ['duration', beet.i64],
      ['extraPercentage', beet.u64],
    ],
    'DurationExtraRewardConfig'
  )
