[test.validator]
url = "https://solana-api.projectserum.com"

[programs.localnet]
unloc_loan = "6oVXrGCdtnTUR6xCvn2Z3f2CYaiboAGar1DKxzeX8QYh"
unloc_staking = "EmS3wD1UF9UhejugSrfUydMzWrCKBCxz4Dr1tBUsodfU"
unloc_voting = "6z6RuFauTG511XRakJnPhxUTCVPohv6oC69xieMdm4Z9"
unloc_burn = "37TgoUgxSshhJmhNEAQMmAWF7XRhXEaY5HxcTZ6eYs6r"

# token metadata
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "local-deploy/mpl_token_metadata.so"

# raydium swap
[[test.genesis]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
program = "local-deploy/raydium-swap-v4.so"

# serum dex v3
[[test.genesis]]
address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
program = "local-deploy/serum-dex-v3.so"

# raydium amm proxy
[[test.genesis]]
address = "BUv45aNgrs7LeGTs69junTor4JfMFkBU8FX6urtG6rpr"
program = "local-deploy/amm_proxy.so"

# chainlink program
[[test.genesis]]
address = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
program = "local-deploy/chainlink.so"

[[test.validator.clone]]
address = "CcPVS9bqyXbD9cLnTbhhHazLsrua8QMFUHTutPtjyDzq"

[[test.validator.clone]]
address = "7CLo1BY41BHAVnEs57kzYMnWXyBJrVEBPpZyQyPo2p1G"

[test]
startup_wait = 1000_000

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn --cwd client/ run ts-mocha -p ./tsconfig.json -t 1000000 tests/spiral-unit-tests/**/*.spec.ts"
 test = "yarn --cwd client/ run ts-mocha -p ./tsconfig.json -t 1000000 tests/spiral-unit-tests/loan/borrower/cancel-sub-offer.spec.ts"
idl = "cp -R target/types client/src"
