
[programs.localnet]
unloc_loan = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
unloc_staking = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
unloc_voting = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
unloc_burn = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./client/tests/test-users/super_owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/tests/**/*.spec.ts"
idl = "cp -R target/types client/src"
