[test.validator]
url = "https://solana-api.projectserum.com"

[programs.localnet]
unloc_loan = "TkpSRsB8yB2qRETXLuPxuZ6Fkg2vuJnmfsQiJLfVpmG"
unloc_staking = "GMdNWaWuQQAMTFr1gWd5VeT6CLbwn6QwiTy3Ek8F6Xvr"
unloc_voting = "7ZQhqWKTKbZZxvRVDVBLTfZneKyTsEyUTQKwbraLyAP3"
unloc_burn = "2v8ZEC4QzHVf9ogZBvwtgasJsiNJfR3EtKqgtH39bTsw"

# Load the program data as accounts to simulate deployed programs.
# [[test.validator.account]]
# address = "TkpSRsB8yB2qRETXLuPxuZ6Fkg2vuJnmfsQiJLfVpmG"
# filename = "target/deploy/accounts/unloc_loan.json"
# [[test.validator.account]]
# address = "3VEi7dWQnEyFvcCzLdXLujuBJVxkzg3LxWJmAioUzFfc"
# filename = "target/deploy/accounts/unloc_loan-exe.json"
# [[test.validator.account]]
# address = "2v8ZEC4QzHVf9ogZBvwtgasJsiNJfR3EtKqgtH39bTsw"
# filename = "target/deploy/accounts/unloc_burn.json"
# [[test.validator.account]]
# address = "4YVNRfztqYCo7r5ziCbWGFrmcNw9jEk99F1kW6EzaUvj"
# filename = "target/deploy/accounts/unloc_burn-exe.json"
# [[test.validator.account]]
# address = "GMdNWaWuQQAMTFr1gWd5VeT6CLbwn6QwiTy3Ek8F6Xvr"
# filename = "target/deploy/accounts/unloc_staking.json"
# [[test.validator.account]]
# address = "9CHEHM8y5HsoxZnkCPFGNRNqLJ7KADrXzgQhsdYdiTgK"
# filename = "target/deploy/accounts/unloc_staking-exe.json"
# [[test.validator.account]]
# address = "7ZQhqWKTKbZZxvRVDVBLTfZneKyTsEyUTQKwbraLyAP3"
# filename = "target/deploy/accounts/unloc_voting.json"
# [[test.validator.account]]
# address = "6s5B4Q7C6pX6AWjTha98a5yVg7DwPCUa4dCA511cduy7"
# filename = "target/deploy/accounts/unloc_voting-exe.json"

# token metadata
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "local-deploy/mpl_token_metadata.so"

# raydium swap
[[test.genesis]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
program = "local-deploy/raydium-swap-v4.so"

# serum dex v3
[[test.genesis]]
address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
program = "local-deploy/serum-dex-v3.so"

# raydium amm proxy
[[test.genesis]]
address = "BUv45aNgrs7LeGTs69junTor4JfMFkBU8FX6urtG6rpr"
program = "local-deploy/amm_proxy.so"

# chainlink program
[[test.genesis]]
address = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
program = "local-deploy/chainlink.so"

[[test.validator.clone]]
address = "CcPVS9bqyXbD9cLnTbhhHazLsrua8QMFUHTutPtjyDzq"

[[test.validator.clone]]
address = "7CLo1BY41BHAVnEs57kzYMnWXyBJrVEBPpZyQyPo2p1G"

[test]
startup_wait = 1000_000

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
gen = "ts-node ./scripts/build.ts"
test = "yarn --cwd client/ run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
idl = "cp -R target/types client/src"
