
[programs.localnet]
unloc_loan = "6oVXrGCdtnTUR6xCvn2Z3f2CYaiboAGar1DKxzeX8QYh"
unloc_staking = "EmS3wD1UF9UhejugSrfUydMzWrCKBCxz4Dr1tBUsodfU"
unloc_voting = "6z6RuFauTG511XRakJnPhxUTCVPohv6oC69xieMdm4Z9"
unloc_burn = "37TgoUgxSshhJmhNEAQMmAWF7XRhXEaY5HxcTZ6eYs6r"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./client/tests/test-users/super_owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/tests/**/*.spec.ts"
idl = "cp -R target/types client/src"
