/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
/**
 * @category enums
 * @category generated
 */
export enum OfferState {
  Proposed,
  Accepted,
  Expired,
  Fulfilled,
  NFTClaimed,
  Canceled,
}

/**
 * @category userTypes
 * @category generated
 */
export const offerStateBeet = beet.fixedScalarEnum(
  OfferState
) as beet.FixedSizeBeet<OfferState, OfferState>
