/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link GlobalState}
 * @category Accounts
 * @category generated
 */
export type GlobalStateArgs = {
  superOwner: web3.PublicKey
  stakingPid: web3.PublicKey
  votingCount: beet.bignum
}

export const globalStateDiscriminator = [163, 46, 74, 168, 216, 123, 133, 98]
/**
 * Holds the data for the {@link GlobalState} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class GlobalState implements GlobalStateArgs {
  private constructor(
    readonly superOwner: web3.PublicKey,
    readonly stakingPid: web3.PublicKey,
    readonly votingCount: beet.bignum
  ) {}

  /**
   * Creates a {@link GlobalState} instance from the provided args.
   */
  static fromArgs(args: GlobalStateArgs) {
    return new GlobalState(args.superOwner, args.stakingPid, args.votingCount)
  }

  /**
   * Deserializes the {@link GlobalState} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [GlobalState, number] {
    return GlobalState.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link GlobalState} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey
  ): Promise<GlobalState> {
    const accountInfo = await connection.getAccountInfo(address)
    if (accountInfo == null) {
      throw new Error(`Unable to find GlobalState account at ${address}`)
    }
    return GlobalState.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Deserializes the {@link GlobalState} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [GlobalState, number] {
    return globalStateBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link GlobalState} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return globalStateBeet.serialize({
      accountDiscriminator: globalStateDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link GlobalState}
   */
  static get byteSize() {
    return globalStateBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link GlobalState} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      GlobalState.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link GlobalState} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === GlobalState.byteSize
  }

  /**
   * Returns a readable version of {@link GlobalState} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      superOwner: this.superOwner.toBase58(),
      stakingPid: this.stakingPid.toBase58(),
      votingCount: (() => {
        const x = <{ toNumber: () => number }>this.votingCount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const globalStateBeet = new beet.BeetStruct<
  GlobalState,
  GlobalStateArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['superOwner', beetSolana.publicKey],
    ['stakingPid', beetSolana.publicKey],
    ['votingCount', beet.u64],
  ],
  GlobalState.fromArgs,
  'GlobalState'
)
