/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link VotingItem}
 * @category Accounts
 * @category generated
 */
export type VotingItemArgs = {
  key: web3.PublicKey
  voting: web3.PublicKey
  votingScore: beet.bignum
}

export const votingItemDiscriminator = [253, 159, 172, 214, 24, 95, 111, 123]
/**
 * Holds the data for the {@link VotingItem} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class VotingItem implements VotingItemArgs {
  private constructor(
    readonly key: web3.PublicKey,
    readonly voting: web3.PublicKey,
    readonly votingScore: beet.bignum
  ) {}

  /**
   * Creates a {@link VotingItem} instance from the provided args.
   */
  static fromArgs(args: VotingItemArgs) {
    return new VotingItem(args.key, args.voting, args.votingScore)
  }

  /**
   * Deserializes the {@link VotingItem} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [VotingItem, number] {
    return VotingItem.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link VotingItem} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey
  ): Promise<VotingItem> {
    const accountInfo = await connection.getAccountInfo(address)
    if (accountInfo == null) {
      throw new Error(`Unable to find VotingItem account at ${address}`)
    }
    return VotingItem.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Deserializes the {@link VotingItem} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [VotingItem, number] {
    return votingItemBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link VotingItem} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return votingItemBeet.serialize({
      accountDiscriminator: votingItemDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link VotingItem}
   */
  static get byteSize() {
    return votingItemBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link VotingItem} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      VotingItem.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link VotingItem} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === VotingItem.byteSize
  }

  /**
   * Returns a readable version of {@link VotingItem} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      key: this.key.toBase58(),
      voting: this.voting.toBase58(),
      votingScore: (() => {
        const x = <{ toNumber: () => number }>this.votingScore
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const votingItemBeet = new beet.BeetStruct<
  VotingItem,
  VotingItemArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['key', beetSolana.publicKey],
    ['voting', beetSolana.publicKey],
    ['votingScore', beet.u128],
  ],
  VotingItem.fromArgs,
  'VotingItem'
)
