/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ChangeFeeVault
 * @category generated
 */
export const changeFeeVaultStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ChangeFeeVaultInstructionArgs'
)
/**
 * Accounts required by the _changeFeeVault_ instruction
 *
 * @property [_writable_] state
 * @property [] feeVault
 * @property [_writable_, **signer**] authority
 * @category Instructions
 * @category ChangeFeeVault
 * @category generated
 */
export type ChangeFeeVaultInstructionAccounts = {
  state: web3.PublicKey
  feeVault: web3.PublicKey
  authority: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const changeFeeVaultInstructionDiscriminator = [
  207, 91, 33, 213, 181, 164, 204, 43,
]

/**
 * Creates a _ChangeFeeVault_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ChangeFeeVault
 * @category generated
 */
export function createChangeFeeVaultInstruction(
  accounts: ChangeFeeVaultInstructionAccounts,
  programId = new web3.PublicKey('EmS3wD1UF9UhejugSrfUydMzWrCKBCxz4Dr1tBUsodfU')
) {
  const [data] = changeFeeVaultStruct.serialize({
    instructionDiscriminator: changeFeeVaultInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.feeVault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
