/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ChangePoolAmountMultipler
 * @category generated
 */
export type ChangePoolAmountMultiplerInstructionArgs = {
  amountMultipler: beet.bignum
}
/**
 * @category Instructions
 * @category ChangePoolAmountMultipler
 * @category generated
 */
export const changePoolAmountMultiplerStruct = new beet.BeetArgsStruct<
  ChangePoolAmountMultiplerInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amountMultipler', beet.u64],
  ],
  'ChangePoolAmountMultiplerInstructionArgs'
)
/**
 * Accounts required by the _changePoolAmountMultipler_ instruction
 *
 * @property [_writable_] state
 * @property [_writable_] pool
 * @property [_writable_, **signer**] authority
 * @property [] clock
 * @category Instructions
 * @category ChangePoolAmountMultipler
 * @category generated
 */
export type ChangePoolAmountMultiplerInstructionAccounts = {
  state: web3.PublicKey
  pool: web3.PublicKey
  authority: web3.PublicKey
  clock: web3.PublicKey
}

export const changePoolAmountMultiplerInstructionDiscriminator = [
  215, 116, 125, 110, 1, 33, 125, 248,
]

/**
 * Creates a _ChangePoolAmountMultipler_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ChangePoolAmountMultipler
 * @category generated
 */
export function createChangePoolAmountMultiplerInstruction(
  accounts: ChangePoolAmountMultiplerInstructionAccounts,
  args: ChangePoolAmountMultiplerInstructionArgs,
  programId = new web3.PublicKey('EmS3wD1UF9UhejugSrfUydMzWrCKBCxz4Dr1tBUsodfU')
) {
  const [data] = changePoolAmountMultiplerStruct.serialize({
    instructionDiscriminator: changePoolAmountMultiplerInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.pool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
