/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ChangeProfileLevels
 * @category generated
 */
export type ChangeProfileLevelsInstructionArgs = {
  profileLevels: beet.bignum[]
}
/**
 * @category Instructions
 * @category ChangeProfileLevels
 * @category generated
 */
export const changeProfileLevelsStruct = new beet.FixableBeetArgsStruct<
  ChangeProfileLevelsInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['profileLevels', beet.array(beet.u128)],
  ],
  'ChangeProfileLevelsInstructionArgs'
)
/**
 * Accounts required by the _changeProfileLevels_ instruction
 *
 * @property [_writable_] state
 * @property [_writable_, **signer**] authority
 * @category Instructions
 * @category ChangeProfileLevels
 * @category generated
 */
export type ChangeProfileLevelsInstructionAccounts = {
  state: web3.PublicKey
  authority: web3.PublicKey
}

export const changeProfileLevelsInstructionDiscriminator = [
  167, 98, 206, 246, 148, 165, 74, 184,
]

/**
 * Creates a _ChangeProfileLevels_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ChangeProfileLevels
 * @category generated
 */
export function createChangeProfileLevelsInstruction(
  accounts: ChangeProfileLevelsInstructionAccounts,
  args: ChangeProfileLevelsInstructionArgs,
  programId = new web3.PublicKey('EmS3wD1UF9UhejugSrfUydMzWrCKBCxz4Dr1tBUsodfU')
) {
  const [data] = changeProfileLevelsStruct.serialize({
    instructionDiscriminator: changeProfileLevelsInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
