/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ChangePoolPoint
 * @category generated
 */
export type ChangePoolPointInstructionArgs = {
  point: beet.bignum
}
/**
 * @category Instructions
 * @category ChangePoolPoint
 * @category generated
 */
export const changePoolPointStruct = new beet.BeetArgsStruct<
  ChangePoolPointInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['point', beet.u64],
  ],
  'ChangePoolPointInstructionArgs'
)
/**
 * Accounts required by the _changePoolPoint_ instruction
 *
 * @property [_writable_] state
 * @property [_writable_] pool
 * @property [_writable_, **signer**] authority
 * @property [] clock
 * @category Instructions
 * @category ChangePoolPoint
 * @category generated
 */
export type ChangePoolPointInstructionAccounts = {
  state: web3.PublicKey
  pool: web3.PublicKey
  authority: web3.PublicKey
  clock: web3.PublicKey
}

export const changePoolPointInstructionDiscriminator = [
  34, 111, 79, 255, 129, 102, 1, 252,
]

/**
 * Creates a _ChangePoolPoint_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ChangePoolPoint
 * @category generated
 */
export function createChangePoolPointInstruction(
  accounts: ChangePoolPointInstructionAccounts,
  args: ChangePoolPointInstructionArgs,
  programId = new web3.PublicKey('EmS3wD1UF9UhejugSrfUydMzWrCKBCxz4Dr1tBUsodfU')
) {
  const [data] = changePoolPointStruct.serialize({
    instructionDiscriminator: changePoolPointInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.pool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
