/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ClosePool
 * @category generated
 */
export const closePoolStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ClosePoolInstructionArgs'
)
/**
 * Accounts required by the _closePool_ instruction
 *
 * @property [_writable_] state
 * @property [_writable_] pool
 * @property [_writable_, **signer**] authority
 * @property [] clock
 * @category Instructions
 * @category ClosePool
 * @category generated
 */
export type ClosePoolInstructionAccounts = {
  state: web3.PublicKey
  pool: web3.PublicKey
  authority: web3.PublicKey
  systemProgram?: web3.PublicKey
  clock: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const closePoolInstructionDiscriminator = [
  140, 189, 209, 23, 239, 62, 239, 11,
]

/**
 * Creates a _ClosePool_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ClosePool
 * @category generated
 */
export function createClosePoolInstruction(
  accounts: ClosePoolInstructionAccounts,
  programId = new web3.PublicKey('EmS3wD1UF9UhejugSrfUydMzWrCKBCxz4Dr1tBUsodfU')
) {
  const [data] = closePoolStruct.serialize({
    instructionDiscriminator: closePoolInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.pool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
