/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  DurationExtraRewardConfig,
  durationExtraRewardConfigBeet,
} from '../types/DurationExtraRewardConfig'

/**
 * @category Instructions
 * @category CreateExtraRewardConfigs
 * @category generated
 */
export type CreateExtraRewardConfigsInstructionArgs = {
  configs: DurationExtraRewardConfig[]
}
/**
 * @category Instructions
 * @category CreateExtraRewardConfigs
 * @category generated
 */
export const createExtraRewardConfigsStruct = new beet.FixableBeetArgsStruct<
  CreateExtraRewardConfigsInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['configs', beet.array(durationExtraRewardConfigBeet)],
  ],
  'CreateExtraRewardConfigsInstructionArgs'
)
/**
 * Accounts required by the _createExtraRewardConfigs_ instruction
 *
 * @property [_writable_] state
 * @property [_writable_] extraRewardAccount
 * @property [_writable_, **signer**] authority
 * @category Instructions
 * @category CreateExtraRewardConfigs
 * @category generated
 */
export type CreateExtraRewardConfigsInstructionAccounts = {
  state: web3.PublicKey
  extraRewardAccount: web3.PublicKey
  authority: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createExtraRewardConfigsInstructionDiscriminator = [
  102, 5, 137, 221, 120, 203, 140, 225,
]

/**
 * Creates a _CreateExtraRewardConfigs_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateExtraRewardConfigs
 * @category generated
 */
export function createCreateExtraRewardConfigsInstruction(
  accounts: CreateExtraRewardConfigsInstructionAccounts,
  args: CreateExtraRewardConfigsInstructionArgs,
  programId = new web3.PublicKey('EmS3wD1UF9UhejugSrfUydMzWrCKBCxz4Dr1tBUsodfU')
) {
  const [data] = createExtraRewardConfigsStruct.serialize({
    instructionDiscriminator: createExtraRewardConfigsInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.extraRewardAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
