/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category Harvest
 * @category generated
 */
export const harvestStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'HarvestInstructionArgs'
)
/**
 * Accounts required by the _harvest_ instruction
 *
 * @property [_writable_] user
 * @property [_writable_] state
 * @property [] extraRewardAccount
 * @property [_writable_] pool
 * @property [_writable_, **signer**] authority
 * @property [] mint
 * @property [_writable_] rewardVault
 * @property [_writable_] userVault
 * @property [] clock
 * @category Instructions
 * @category Harvest
 * @category generated
 */
export type HarvestInstructionAccounts = {
  user: web3.PublicKey
  state: web3.PublicKey
  extraRewardAccount: web3.PublicKey
  pool: web3.PublicKey
  authority: web3.PublicKey
  mint: web3.PublicKey
  rewardVault: web3.PublicKey
  userVault: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  clock: web3.PublicKey
}

export const harvestInstructionDiscriminator = [
  228, 241, 31, 182, 53, 169, 59, 199,
]

/**
 * Creates a _Harvest_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category Harvest
 * @category generated
 */
export function createHarvestInstruction(
  accounts: HarvestInstructionAccounts,
  programId = new web3.PublicKey('EmS3wD1UF9UhejugSrfUydMzWrCKBCxz4Dr1tBUsodfU')
) {
  const [data] = harvestStruct.serialize({
    instructionDiscriminator: harvestInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.user,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.extraRewardAccount,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.pool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rewardVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
