/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Offer}
 * @category Accounts
 * @category generated
 */
export type OfferArgs = {
  bump: number
  borrower: web3.PublicKey
  nftMint: web3.PublicKey
  collection: web3.PublicKey
  state: number
  subOfferCount: beet.bignum
  startSubOfferNum: beet.bignum
  creationDate: beet.bignum
  reserved: beet.bignum[] /* size: 7 */
}

export const offerDiscriminator = [215, 88, 60, 71, 170, 162, 73, 229]
/**
 * Holds the data for the {@link Offer} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Offer implements OfferArgs {
  private constructor(
    readonly bump: number,
    readonly borrower: web3.PublicKey,
    readonly nftMint: web3.PublicKey,
    readonly collection: web3.PublicKey,
    readonly state: number,
    readonly subOfferCount: beet.bignum,
    readonly startSubOfferNum: beet.bignum,
    readonly creationDate: beet.bignum,
    readonly reserved: beet.bignum[] /* size: 7 */
  ) {}

  /**
   * Creates a {@link Offer} instance from the provided args.
   */
  static fromArgs(args: OfferArgs) {
    return new Offer(
      args.bump,
      args.borrower,
      args.nftMint,
      args.collection,
      args.state,
      args.subOfferCount,
      args.startSubOfferNum,
      args.creationDate,
      args.reserved
    )
  }

  /**
   * Deserializes the {@link Offer} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Offer, number] {
    return Offer.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Offer} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey
  ): Promise<Offer> {
    const accountInfo = await connection.getAccountInfo(address)
    if (accountInfo == null) {
      throw new Error(`Unable to find Offer account at ${address}`)
    }
    return Offer.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Deserializes the {@link Offer} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Offer, number] {
    return offerBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Offer} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return offerBeet.serialize({
      accountDiscriminator: offerDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Offer}
   */
  static get byteSize() {
    return offerBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Offer} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Offer.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Offer} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Offer.byteSize
  }

  /**
   * Returns a readable version of {@link Offer} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      borrower: this.borrower.toBase58(),
      nftMint: this.nftMint.toBase58(),
      collection: this.collection.toBase58(),
      state: this.state,
      subOfferCount: (() => {
        const x = <{ toNumber: () => number }>this.subOfferCount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      startSubOfferNum: (() => {
        const x = <{ toNumber: () => number }>this.startSubOfferNum
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      creationDate: (() => {
        const x = <{ toNumber: () => number }>this.creationDate
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      reserved: this.reserved,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const offerBeet = new beet.BeetStruct<
  Offer,
  OfferArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['borrower', beetSolana.publicKey],
    ['nftMint', beetSolana.publicKey],
    ['collection', beetSolana.publicKey],
    ['state', beet.u8],
    ['subOfferCount', beet.u64],
    ['startSubOfferNum', beet.u64],
    ['creationDate', beet.u64],
    ['reserved', beet.uniformFixedSizeArray(beet.u128, 7)],
  ],
  Offer.fromArgs,
  'Offer'
)
